# Generated by Django 6.0.4 on 2026-04-20 12:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('risk_score', models.CharField(choices=[('LOW', 'Low (Green)'), ('MEDIUM', 'Medium (Orange)'), ('HIGH', 'High (Red)')], default='LOW', max_length=10)),
                ('suspicious_urls', models.JSONField(blank=True, default=list)),
                ('header_anomalies', models.JSONField(blank=True, default=list)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
