# Generated by Django 6.0.4 on 2026-05-15 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0002_scanreport_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicator_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('indicator_type', models.CharField(choices=[('URL', 'URL Hash'), ('MD5', 'File MD5'), ('SHA256', 'File SHA256')], max_length=10)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
