# Generated by Django 6.0.4 on 2026-05-10 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanreport',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
